In [23]:
import pandas as pd
import random

random.seed(42)

examples = []

def add_example(subject, grade_band, topic, context, question, answer):
    examples.append({
        "subject": subject,
        "grade_band": grade_band,
        "topic": topic,
        "context": context,
        "question": question,
        "answer": answer
    })

# ---------------------------
# Math
# ---------------------------
math_topics = [
    {
        "topic": "addition",
        "grade_band": "K-2",
        "context": "Addition means combining two or more numbers to find the total.",
        "qas": [
            ("What does addition mean?", "Addition means putting numbers together to find the total."),
            ("What is 4 + 3?", "4 + 3 = 7."),
            ("If you have 2 apples and get 5 more, how many apples do you have?", "You have 7 apples."),
            ("Why do we use addition?", "We use addition to combine amounts and find the total.")
        ]
    },
    {
        "topic": "subtraction",
        "grade_band": "K-2",
        "context": "Subtraction means taking one number away from another to find how many are left.",
        "qas": [
            ("What does subtraction mean?", "Subtraction means taking away to find how many are left."),
            ("What is 9 - 4?", "9 - 4 = 5."),
            ("If you have 8 cookies and eat 3, how many are left?", "There are 5 cookies left."),
            ("When do we use subtraction?", "We use subtraction when we take away or compare amounts.")
        ]
    },
    {
        "topic": "multiplication",
        "grade_band": "3-5",
        "context": "Multiplication is repeated addition. For example, 3 × 4 means 3 groups of 4.",
        "qas": [
            ("What is multiplication?", "Multiplication is repeated addition or equal groups."),
            ("What is 6 × 7?", "6 × 7 = 42."),
            ("What does 4 × 3 mean?", "It means 4 groups of 3 or 3 + 3 + 3 + 3."),
            ("Why is multiplication useful?", "It helps us count equal groups quickly.")
        ]
    },
    {
        "topic": "division",
        "grade_band": "3-5",
        "context": "Division means splitting into equal groups or finding how many times one number fits into another.",
        "qas": [
            ("What is division?", "Division is splitting into equal groups."),
            ("What is 20 ÷ 5?", "20 ÷ 5 = 4."),
            ("If 12 pencils are shared equally among 3 students, how many does each get?", "Each student gets 4 pencils."),
            ("How is division related to multiplication?", "Division undoes multiplication.")
        ]
    },
    {
        "topic": "fractions",
        "grade_band": "3-5",
        "context": "A fraction represents part of a whole. The numerator shows how many parts are taken, and the denominator shows the total equal parts.",
        "qas": [
            ("What is a fraction?", "A fraction is a part of a whole."),
            ("What does 1/2 mean?", "It means 1 out of 2 equal parts."),
            ("Which is bigger, 1/4 or 1/2?", "1/2 is bigger than 1/4."),
            ("What does the denominator show?", "The denominator shows the total number of equal parts.")
        ]
    },
    {
        "topic": "decimals",
        "grade_band": "4-6",
        "context": "Decimals are another way to represent parts of a whole, especially based on tenths and hundredths.",
        "qas": [
            ("What is a decimal?", "A decimal shows part of a whole using place value like tenths and hundredths."),
            ("Which is greater, 0.8 or 0.25?", "0.8 is greater than 0.25."),
            ("What does the 5 mean in 0.5?", "It means 5 tenths."),
            ("How are fractions and decimals related?", "They can represent the same value in different forms.")
        ]
    },
    {
        "topic": "place value",
        "grade_band": "2-4",
        "context": "Place value tells the value of a digit based on its position in a number.",
        "qas": [
            ("What is place value?", "Place value tells how much a digit is worth based on where it is."),
            ("What is the value of 3 in 345?", "The 3 has a value of 300."),
            ("What is the value of 7 in 274?", "The 7 has a value of 70."),
            ("Why is place value important?", "It helps us read, compare, and compute with numbers.")
        ]
    },
    {
        "topic": "area and perimeter",
        "grade_band": "3-5",
        "context": "Perimeter is the distance around a shape. Area is the amount of space inside a shape.",
        "qas": [
            ("What is perimeter?", "Perimeter is the distance around a shape."),
            ("What is area?", "Area is the amount of space inside a shape."),
            ("What is the perimeter of a rectangle with sides 4 and 6?", "The perimeter is 20 units."),
            ("What is the area of a rectangle with sides 4 and 6?", "The area is 24 square units.")
        ]
    },
    {
        "topic": "ratios",
        "grade_band": "6-8",
        "context": "A ratio compares two quantities. It can be written as a:b, a to b, or a/b.",
        "qas": [
            ("What is a ratio?", "A ratio compares two quantities."),
            ("How can a ratio be written?", "It can be written as a:b, a to b, or a/b."),
            ("What does a ratio of 2:3 mean?", "It means for every 2 of one quantity, there are 3 of another."),
            ("Why do we use ratios?", "We use ratios to compare amounts and describe relationships.")
        ]
    },
    {
        "topic": "percentages",
        "grade_band": "6-8",
        "context": "A percentage means 'out of 100.' For example, 25% means 25 out of 100.",
        "qas": [
            ("What does percent mean?", "Percent means out of 100."),
            ("What is 50% as a fraction?", "50% is 1/2."),
            ("What is 25% of 200?", "25% of 200 is 50."),
            ("Why are percentages useful?", "They help compare parts of a whole in a standard way.")
        ]
    },
    {
        "topic": "linear equations",
        "grade_band": "7-9",
        "context": "A linear equation is an equation in which the highest power of the variable is 1. Solving means finding the value of the variable that makes the equation true.",
        "qas": [
            ("What is a linear equation?", "A linear equation has a variable with highest power 1."),
            ("What does it mean to solve an equation?", "It means to find the value of the variable that makes the equation true."),
            ("Solve x + 5 = 12.", "x = 7."),
            ("Solve 2x = 14.", "x = 7.")
        ]
    },
    {
        "topic": "slope",
        "grade_band": "8-10",
        "context": "Slope measures the steepness of a line and is calculated as rise over run.",
        "qas": [
            ("What is slope?", "Slope measures the steepness of a line."),
            ("How do you calculate slope?", "Slope is calculated as rise over run."),
            ("What does a positive slope mean?", "It means the line goes up from left to right."),
            ("What does a zero slope mean?", "It means the line is horizontal.")
        ]
    }
]

for block in math_topics:
    for q, a in block["qas"]:
        add_example("Math", block["grade_band"], block["topic"], block["context"], q, a)

# ---------------------------
# Science
# ---------------------------
science_topics = [
    {
        "topic": "states of matter",
        "grade_band": "2-5",
        "context": "Matter has mass and takes up space. Common states of matter are solid, liquid, and gas.",
        "qas": [
            ("What is matter?", "Matter is anything that has mass and takes up space."),
            ("What are the three common states of matter?", "The three common states are solid, liquid, and gas."),
            ("What shape does a liquid have?", "A liquid takes the shape of its container."),
            ("How is a gas different from a solid?", "A gas spreads out to fill space, while a solid keeps its shape.")
        ]
    },
    {
        "topic": "plant life cycle",
        "grade_band": "2-5",
        "context": "Plants grow from seeds. They need water, sunlight, air, and nutrients to grow.",
        "qas": [
            ("What do plants need to grow?", "Plants need water, sunlight, air, and nutrients."),
            ("Where do many plants begin?", "Many plants begin as seeds."),
            ("Why is sunlight important for plants?", "Sunlight helps plants make food through photosynthesis."),
            ("What is a plant life cycle?", "It is the series of stages a plant goes through as it grows and reproduces.")
        ]
    },
    {
        "topic": "photosynthesis",
        "grade_band": "4-7",
        "context": "Photosynthesis is the process plants use to make food using sunlight, water, and carbon dioxide.",
        "qas": [
            ("What is photosynthesis?", "Photosynthesis is how plants make food using sunlight, water, and carbon dioxide."),
            ("Why is photosynthesis important?", "It provides food for plants and helps produce oxygen."),
            ("What do plants use during photosynthesis?", "Plants use sunlight, water, and carbon dioxide."),
            ("What is produced during photosynthesis?", "Plants make sugar and release oxygen.")
        ]
    },
    {
        "topic": "ecosystems",
        "grade_band": "4-7",
        "context": "An ecosystem is a community of living and nonliving things interacting in an environment.",
        "qas": [
            ("What is an ecosystem?", "An ecosystem is a community of living and nonliving things interacting."),
            ("What are biotic factors?", "Biotic factors are the living parts of an ecosystem."),
            ("What are abiotic factors?", "Abiotic factors are the nonliving parts like water, sunlight, and soil."),
            ("Why are ecosystems important?", "They support life by connecting organisms with their environment.")
        ]
    },
    {
        "topic": "food chains",
        "grade_band": "3-6",
        "context": "A food chain shows how energy moves from one organism to another, starting often with the sun and producers.",
        "qas": [
            ("What is a food chain?", "A food chain shows how energy moves between organisms."),
            ("What is a producer?", "A producer is an organism like a plant that makes its own food."),
            ("What is a consumer?", "A consumer is an organism that gets energy by eating other organisms."),
            ("Why does a food chain often start with the sun?", "Because the sun provides energy for plants.")
        ]
    },
    {
        "topic": "weather vs climate",
        "grade_band": "4-7",
        "context": "Weather describes short-term atmospheric conditions, while climate describes long-term patterns in a region.",
        "qas": [
            ("What is weather?", "Weather is the short-term condition of the atmosphere."),
            ("What is climate?", "Climate is the long-term pattern of weather in a region."),
            ("How are weather and climate different?", "Weather is short-term, while climate is long-term."),
            ("Why do scientists study climate?", "They study climate to understand long-term environmental patterns.")
        ]
    },
    {
        "topic": "solar system",
        "grade_band": "3-6",
        "context": "The solar system includes the sun, planets, moons, and other objects that orbit the sun.",
        "qas": [
            ("What is the solar system?", "The solar system is the sun and all the objects that orbit it."),
            ("What do planets do in the solar system?", "Planets orbit the sun."),
            ("What is at the center of the solar system?", "The sun is at the center of the solar system."),
            ("Why does Earth stay in orbit around the sun?", "Earth stays in orbit because of gravity.")
        ]
    },
    {
        "topic": "force and motion",
        "grade_band": "4-8",
        "context": "A force is a push or pull. Forces can change an object's motion by starting, stopping, speeding up, or changing direction.",
        "qas": [
            ("What is a force?", "A force is a push or a pull."),
            ("How can force affect motion?", "Force can start, stop, speed up, slow down, or change direction."),
            ("What is motion?", "Motion is a change in position over time."),
            ("What does friction do?", "Friction resists motion between surfaces.")
        ]
    },
    {
        "topic": "atoms and molecules",
        "grade_band": "6-8",
        "context": "Atoms are tiny units of matter. Molecules form when atoms bond together.",
        "qas": [
            ("What is an atom?", "An atom is a tiny unit of matter."),
            ("What is a molecule?", "A molecule is made of two or more atoms bonded together."),
            ("How are atoms and molecules related?", "Molecules are formed when atoms join together."),
            ("Why are atoms important?", "Atoms are the building blocks of matter.")
        ]
    },
    {
        "topic": "cell structure",
        "grade_band": "6-9",
        "context": "Cells are the basic units of life. Important cell parts include the membrane, nucleus, and cytoplasm.",
        "qas": [
            ("What is a cell?", "A cell is the basic unit of life."),
            ("What does the nucleus do?", "The nucleus contains genetic material and helps control the cell."),
            ("What does the cell membrane do?", "The cell membrane controls what enters and leaves the cell."),
            ("Why are cells important?", "All living things are made of cells.")
        ]
    },
    {
        "topic": "energy transfer",
        "grade_band": "5-8",
        "context": "Energy can be transferred by conduction, convection, and radiation.",
        "qas": [
            ("What is conduction?", "Conduction is heat transfer through direct contact."),
            ("What is convection?", "Convection is heat transfer through movement of fluids like air or water."),
            ("What is radiation?", "Radiation is energy transfer by waves and does not require matter."),
            ("Why is energy transfer important?", "It explains how heat moves from one place to another.")
        ]
    },
    {
        "topic": "scientific method",
        "grade_band": "4-8",
        "context": "The scientific method often includes asking a question, making a hypothesis, testing it, analyzing results, and drawing conclusions.",
        "qas": [
            ("What is the scientific method?", "It is a process for investigating questions through observation and experiments."),
            ("What is a hypothesis?", "A hypothesis is a testable explanation or prediction."),
            ("Why do scientists run experiments?", "They run experiments to test hypotheses."),
            ("Why is analyzing results important?", "It helps determine whether the evidence supports the hypothesis.")
        ]
    }
]

for block in science_topics:
    for q, a in block["qas"]:
        add_example("Science", block["grade_band"], block["topic"], block["context"], q, a)

# ---------------------------
# English Language Arts
# ---------------------------
ela_topics = [
    {
        "topic": "main idea",
        "grade_band": "3-6",
        "context": "The main idea is the most important point the author wants the reader to understand.",
        "qas": [
            ("What is the main idea?", "The main idea is the most important point in a text."),
            ("How do you find the main idea?", "Look for the overall message and key supporting details."),
            ("Why is the main idea important?", "It helps readers understand what the text is mostly about."),
            ("What supports the main idea?", "Details and examples support the main idea.")
        ]
    },
    {
        "topic": "summary",
        "grade_band": "3-6",
        "context": "A summary is a short retelling of the most important parts of a text in your own words.",
        "qas": [
            ("What is a summary?", "A summary is a short retelling of the main points of a text."),
            ("Why should a summary be shorter than the original text?", "Because it includes only the most important information."),
            ("Should a summary include every detail?", "No, it should focus on the key ideas."),
            ("Why is summarizing useful?", "It helps readers understand and remember important information.")
        ]
    },
    {
        "topic": "author's purpose",
        "grade_band": "4-7",
        "context": "An author's purpose may be to inform, persuade, entertain, or explain.",
        "qas": [
            ("What is an author's purpose?", "An author's purpose is the reason the author wrote the text."),
            ("What are common author's purposes?", "Common purposes are to inform, persuade, entertain, or explain."),
            ("How can you tell if a text is persuasive?", "It tries to convince the reader of something."),
            ("Why does author's purpose matter?", "It helps readers understand the writer's goal.")
        ]
    },
    {
        "topic": "theme",
        "grade_band": "5-8",
        "context": "A theme is a message or lesson about life that a reader can infer from a story.",
        "qas": [
            ("What is a theme?", "A theme is a message or lesson in a story."),
            ("How is theme different from main idea?", "Theme is a life lesson or message, while main idea is what the text is mostly about."),
            ("Can a story have more than one theme?", "Yes, a story can have multiple themes."),
            ("How do readers find a theme?", "They look at the characters, events, and lessons in the story.")
        ]
    },
    {
        "topic": "figurative language",
        "grade_band": "4-8",
        "context": "Figurative language includes similes, metaphors, personification, and idioms. It adds vivid meaning to writing.",
        "qas": [
            ("What is figurative language?", "Figurative language uses words in imaginative ways to create meaning."),
            ("What is a simile?", "A simile compares two things using like or as."),
            ("What is a metaphor?", "A metaphor compares two unlike things by saying one is the other."),
            ("Why do writers use figurative language?", "Writers use it to make writing more vivid and expressive.")
        ]
    },
    {
        "topic": "parts of speech",
        "grade_band": "2-5",
        "context": "Parts of speech include nouns, verbs, adjectives, adverbs, pronouns, prepositions, conjunctions, and interjections.",
        "qas": [
            ("What is a noun?", "A noun names a person, place, thing, or idea."),
            ("What is a verb?", "A verb shows an action or a state of being."),
            ("What is an adjective?", "An adjective describes a noun."),
            ("What is an adverb?", "An adverb describes a verb, adjective, or another adverb.")
        ]
    },
    {
        "topic": "sentence types",
        "grade_band": "2-5",
        "context": "Sentences can be declarative, interrogative, imperative, or exclamatory.",
        "qas": [
            ("What is a declarative sentence?", "A declarative sentence makes a statement."),
            ("What is an interrogative sentence?", "An interrogative sentence asks a question."),
            ("What is an imperative sentence?", "An imperative sentence gives a command or request."),
            ("What is an exclamatory sentence?", "An exclamatory sentence shows strong feeling.")
        ]
    },
    {
        "topic": "reading inference",
        "grade_band": "4-8",
        "context": "An inference is a conclusion a reader makes using clues from the text and prior knowledge.",
        "qas": [
            ("What is an inference?", "An inference is a conclusion based on clues and prior knowledge."),
            ("Do writers always state everything directly?", "No, readers often need to infer meaning."),
            ("What helps a reader make an inference?", "Text evidence and what the reader already knows."),
            ("Why are inferences important?", "They help readers understand deeper meaning.")
        ]
    },
    {
        "topic": "compare and contrast",
        "grade_band": "3-6",
        "context": "To compare means to find similarities. To contrast means to find differences.",
        "qas": [
            ("What does compare mean?", "Compare means to identify similarities."),
            ("What does contrast mean?", "Contrast means to identify differences."),
            ("Why do readers compare and contrast texts?", "It helps them understand relationships between ideas."),
            ("What is a similarity?", "A similarity is something two things have in common.")
        ]
    },
    {
        "topic": "writing process",
        "grade_band": "4-8",
        "context": "The writing process often includes planning, drafting, revising, editing, and publishing.",
        "qas": [
            ("What is the writing process?", "It is the set of steps writers use to create and improve writing."),
            ("What happens during drafting?", "The writer creates the first version of the piece."),
            ("What happens during revising?", "The writer improves ideas, structure, and clarity."),
            ("What happens during editing?", "The writer fixes grammar, spelling, and punctuation.")
        ]
    }
]

for block in ela_topics:
    for q, a in block["qas"]:
        add_example("ELA", block["grade_band"], block["topic"], block["context"], q, a)

# ---------------------------
# Social Studies / History / Civics
# ---------------------------
ss_topics = [
    {
        "topic": "communities",
        "grade_band": "K-3",
        "context": "A community is a group of people living, working, or helping one another in the same place or with shared interests.",
        "qas": [
            ("What is a community?", "A community is a group of people who live or work together or share something in common."),
            ("Why are communities important?", "Communities help people work together and support one another."),
            ("Who are community helpers?", "Community helpers are people like teachers, firefighters, and doctors who help others."),
            ("What do community helpers do?", "They provide important services that help people stay safe and healthy.")
        ]
    },
    {
        "topic": "maps and globes",
        "grade_band": "2-5",
        "context": "Maps represent places on a flat surface, while globes are round models of Earth.",
        "qas": [
            ("What is a map?", "A map is a drawing that shows places on a flat surface."),
            ("What is a globe?", "A globe is a round model of Earth."),
            ("How is a map different from a globe?", "A map is flat, while a globe is round."),
            ("Why do we use maps?", "We use maps to locate places and understand geography.")
        ]
    },
    {
        "topic": "government",
        "grade_band": "3-6",
        "context": "Government is the system people use to make laws, provide services, and maintain order.",
        "qas": [
            ("What is government?", "Government is a system for making laws and helping society function."),
            ("Why do societies need government?", "They need government to make rules, provide services, and maintain order."),
            ("What is a law?", "A law is a rule made by a government."),
            ("Why are laws important?", "Laws help keep people safe and organize society.")
        ]
    },
    {
        "topic": "branches of government",
        "grade_band": "4-8",
        "context": "The U.S. government has three branches: legislative, executive, and judicial. They share power through checks and balances.",
        "qas": [
            ("What are the three branches of government?", "The three branches are legislative, executive, and judicial."),
            ("What does the legislative branch do?", "It makes laws."),
            ("What does the executive branch do?", "It carries out and enforces laws."),
            ("What does the judicial branch do?", "It interprets laws.")
        ]
    },
    {
        "topic": "citizenship",
        "grade_band": "3-7",
        "context": "Citizenship includes rights and responsibilities such as obeying laws, voting when eligible, and helping the community.",
        "qas": [
            ("What is citizenship?", "Citizenship is being a member of a country with rights and responsibilities."),
            ("What is one responsibility of citizens?", "One responsibility is obeying laws."),
            ("What is one right of citizens?", "One right is participating in civic life, such as voting when eligible."),
            ("Why is responsible citizenship important?", "It helps communities and countries function well.")
        ]
    },
    {
        "topic": "historical sources",
        "grade_band": "4-8",
        "context": "Primary sources come from the time being studied, while secondary sources explain or analyze primary sources later.",
        "qas": [
            ("What is a primary source?", "A primary source comes directly from the time being studied."),
            ("What is a secondary source?", "A secondary source explains or analyzes events after they happened."),
            ("Is a diary a primary source?", "Yes, if it was written during the time being studied."),
            ("Why are historical sources important?", "They help us understand the past using evidence.")
        ]
    },
    {
        "topic": "economics basics",
        "grade_band": "4-8",
        "context": "Economics studies how people use resources to make, buy, and sell goods and services.",
        "qas": [
            ("What is economics?", "Economics is the study of how people use resources."),
            ("What is a good?", "A good is a physical item people buy or use."),
            ("What is a service?", "A service is work done for someone else."),
            ("Why are resources important in economics?", "Resources are needed to produce goods and services.")
        ]
    },
    {
        "topic": "supply and demand",
        "grade_band": "5-9",
        "context": "Supply is how much of something is available. Demand is how much people want it.",
        "qas": [
            ("What is supply?", "Supply is the amount of a product available."),
            ("What is demand?", "Demand is how much people want a product."),
            ("What may happen if demand increases a lot and supply stays low?", "Prices may rise."),
            ("Why do supply and demand matter?", "They help explain prices and markets.")
        ]
    },
    {
        "topic": "American Revolution",
        "grade_band": "5-8",
        "context": "The American Revolution was a conflict in which the American colonies fought for independence from Britain.",
        "qas": [
            ("What was the American Revolution?", "It was a war in which the American colonies fought for independence from Britain."),
            ("Why is the American Revolution important?", "It led to the creation of the United States."),
            ("What does independence mean?", "Independence means self-rule or freedom from control by another country."),
            ("Who fought in the American Revolution?", "The American colonies fought against Britain.")
        ]
    },
    {
        "topic": "Constitution",
        "grade_band": "5-8",
        "context": "The U.S. Constitution is the supreme law of the land and explains the structure of the federal government.",
        "qas": [
            ("What is the Constitution?", "The Constitution is the supreme law of the United States."),
            ("Why is the Constitution important?", "It explains how the government is organized and what powers it has."),
            ("What does supreme law mean?", "It means the highest law that other laws must follow."),
            ("What does the Constitution help protect?", "It helps protect rights and define government powers.")
        ]
    }
]

for block in ss_topics:
    for q, a in block["qas"]:
        add_example("Social Studies", block["grade_band"], block["topic"], block["context"], q, a)

# ---------------------------
# Study Skills / General Academic
# ---------------------------
study_topics = [
    {
        "topic": "goal setting",
        "grade_band": "3-12",
        "context": "Good academic goals are specific, measurable, realistic, and time-bound.",
        "qas": [
            ("What makes a good academic goal?", "A good academic goal is specific, measurable, realistic, and time-bound."),
            ("Why is goal setting important?", "Goal setting helps students stay focused and track progress."),
            ("What does measurable mean in a goal?", "It means you can track whether you are making progress."),
            ("Why should a goal be realistic?", "A realistic goal is more achievable and motivating.")
        ]
    },
    {
        "topic": "note-taking",
        "grade_band": "4-12",
        "context": "Effective note-taking means writing down key ideas, examples, and questions in a clear and organized way.",
        "qas": [
            ("What is effective note-taking?", "Effective note-taking means recording key ideas clearly and in an organized way."),
            ("Why is note-taking useful?", "It helps students remember and review important information."),
            ("What should notes include?", "Notes should include main ideas, important details, and questions."),
            ("Why should notes be organized?", "Organized notes are easier to review and understand later.")
        ]
    },
    {
        "topic": "time management",
        "grade_band": "5-12",
        "context": "Time management means planning how to use time effectively for studying, homework, rest, and other responsibilities.",
        "qas": [
            ("What is time management?", "Time management is planning how to use time effectively."),
            ("Why is time management important for students?", "It helps students complete work on time and reduce stress."),
            ("What is one good time management strategy?", "Breaking large tasks into smaller steps is a good strategy."),
            ("Why should students use a schedule?", "A schedule helps them plan tasks and stay organized.")
        ]
    },
    {
        "topic": "test preparation",
        "grade_band": "5-12",
        "context": "Good test preparation includes reviewing notes regularly, practicing problems, and getting enough rest.",
        "qas": [
            ("How can students prepare well for a test?", "They can review notes regularly, practice, and get enough rest."),
            ("Why is practicing important before a test?", "Practicing helps strengthen understanding and confidence."),
            ("Why does sleep matter before a test?", "Sleep helps memory, focus, and thinking."),
            ("Is last-minute cramming the best strategy?", "No, regular review is usually more effective.")
        ]
    },
    {
        "topic": "growth mindset",
        "grade_band": "3-12",
        "context": "A growth mindset is the belief that abilities can improve through effort, practice, and learning.",
        "qas": [
            ("What is a growth mindset?", "A growth mindset is the belief that abilities can improve with effort and learning."),
            ("Why is a growth mindset helpful?", "It encourages persistence and learning from mistakes."),
            ("How is a growth mindset different from a fixed mindset?", "A growth mindset believes abilities can improve, while a fixed mindset assumes they cannot change much."),
            ("What should students do when they make mistakes?", "They should view mistakes as chances to learn and improve.")
        ]
    }
]

for block in study_topics:
    for q, a in block["qas"]:
        add_example("Study Skills", block["grade_band"], block["topic"], block["context"], q, a)

# ---------------------------
# Expand with paraphrase templates
# ---------------------------
paraphrase_templates = [
    ("Can you explain {topic}?", "Sure. {short_answer}"),
    ("Why is {topic} important?", "{importance_answer}"),
    ("Give a simple definition of {topic}.", "{definition_answer}"),
]

topic_metadata = [
    ("fractions", "Fractions represent parts of a whole.", "Fractions are important because they help describe parts of a whole and compare quantities.", "Fractions are parts of a whole."),
    ("photosynthesis", "Photosynthesis is how plants make food using sunlight, water, and carbon dioxide.", "Photosynthesis is important because it helps plants make food and supports life on Earth.", "Photosynthesis is the process plants use to make food."),
    ("government", "Government is a system that makes laws and helps society function.", "Government is important because it helps maintain order, provide services, and protect people.", "Government is a system for making laws and organizing society."),
    ("theme", "Theme is the message or lesson in a story.", "Theme is important because it helps readers understand deeper meaning in literature.", "Theme is the lesson or message of a text."),
    ("time management", "Time management means planning time effectively.", "Time management is important because it helps students stay organized and reduce stress.", "Time management is the skill of planning how to use time well."),
    ("slope", "Slope measures the steepness of a line.", "Slope is important because it helps describe how lines change and compare rates.", "Slope is a measure of a line's steepness."),
    ("ecosystems", "An ecosystem is a community of living and nonliving things interacting.", "Ecosystems are important because they support life and show how organisms depend on one another.", "An ecosystem is a system of living and nonliving things interacting."),
    ("author's purpose", "Author's purpose is the reason the writer created the text.", "Author's purpose is important because it helps readers understand the writer's goal.", "Author's purpose is the writer's reason for writing."),
    ("Constitution", "The Constitution is the highest law of the United States.", "The Constitution is important because it defines government powers and protects rights.", "The Constitution is the supreme law of the land."),
    ("growth mindset", "A growth mindset is the belief that abilities can improve.", "A growth mindset is important because it helps students persevere and learn from mistakes.", "A growth mindset is the belief that learning and effort can improve ability.")
]

for topic, short_answer, importance_answer, definition_answer in topic_metadata:
    for q_template, a_template in paraphrase_templates:
        add_example(
            "Mixed",
            "K-12",
            topic,
            f"This example is about {topic} in a K-12 academic setting.",
            q_template.format(topic=topic),
            a_template.format(
                topic=topic,
                short_answer=short_answer,
                importance_answer=importance_answer,
                definition_answer=definition_answer
            )
        )

df = pd.DataFrame(examples)

print("Total examples:", len(df))
df.head()

Total examples: 226

,subject,grade_band,topic,context,question,answer
0,Math,K-2,addition,Addition means combining two or more numbers t...,What does addition mean?,Addition means putting numbers together to fin...
1,Math,K-2,addition,Addition means combining two or more numbers t...,What is 4 + 3?,4 + 3 = 7.
2,Math,K-2,addition,Addition means combining two or more numbers t...,"If you have 2 apples and get 5 more, how many ...",You have 7 apples.
3,Math,K-2,addition,Addition means combining two or more numbers t...,Why do we use addition?,We use addition to combine amounts and find th...
4,Math,K-2,subtraction,Subtraction means taking one number away from ...,What does subtraction mean?,Subtraction means taking away to find how many...

In [24]:
df["subject"].value_counts()

subject
Math              48
Science           48
ELA               40
Social Studies    40
Mixed             30
Study Skills      20
Name: count, dtype: int64

In [25]:
df[["subject", "grade_band", "topic"]].head(10)

  subject grade_band           topic
0    Math        K-2        addition
1    Math        K-2        addition
2    Math        K-2        addition
3    Math        K-2        addition
4    Math        K-2     subtraction
5    Math        K-2     subtraction
6    Math        K-2     subtraction
7    Math        K-2     subtraction
8    Math        3-5  multiplication
9    Math        3-5  multiplication

In [26]:
df.to_csv("k12_qa_dataset.csv", index=False)

df.to_json("k12_qa_dataset.jsonl", orient="records", lines=True)

print("Saved files:")
print("- k12_qa_dataset.csv")
print("- k12_qa_dataset.jsonl")

Saved files:
- k12_qa_dataset.csv
- k12_qa_dataset.jsonl

In [27]:
print("Total examples:", len(df))
df["subject"].value_counts()

Total examples: 226

subject
Math              48
Science           48
ELA               40
Social Studies    40
Mixed             30
Study Skills      20
Name: count, dtype: int64

In [28]:
def format_prompt(row):
    return f"""You are a helpful K-12 academic assistant. Answer the student's question using the provided academic context.

Subject: {row['subject']}
Grade Band: {row['grade_band']}
Topic: {row['topic']}

Context:
{row['context']}

Question:
{row['question']}

Answer:
{row['answer']}"""

df["text"] = df.apply(format_prompt, axis=1)

print(df["text"].iloc[0])

You are a helpful K-12 academic assistant. Answer the student's question using the provided academic context.

Subject: Math
Grade Band: K-2
Topic: addition

Context:
Addition means combining two or more numbers to find the total.

Question:
What does addition mean?

Answer:
Addition means putting numbers together to find the total.

In [29]:
from datasets import Dataset

hf_dataset = Dataset.from_pandas(df[["text"]])
hf_dataset

Dataset({
    features: ['text'],
    num_rows: 226
})

In [30]:
split_dataset = hf_dataset.train_test_split(test_size=0.1, seed=42)

train_dataset = split_dataset["train"]
val_dataset = split_dataset["test"]

print("Train size:", len(train_dataset))
print("Validation size:", len(val_dataset))

Train size: 203
Validation size: 23

In [31]:
print(train_dataset[0]["text"])

You are a helpful K-12 academic assistant. Answer the student's question using the provided academic context.

Subject: Mixed
Grade Band: K-12
Topic: photosynthesis

Context:
This example is about photosynthesis in a K-12 academic setting.

Question:
Why is photosynthesis important?

Answer:
Photosynthesis is important because it helps plants make food and supports life on Earth.

In [32]:
!pip install -q transformers datasets peft accelerate bitsandbytes trl

In [33]:
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments
)

from peft import LoraConfig, prepare_model_for_kbit_training
from trl import SFTTrainer

In [34]:
model_name = "Qwen/Qwen2.5-1.5B-Instruct"

In [35]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True
)

In [36]:
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [37]:
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [38]:
model = prepare_model_for_kbit_training(model)

In [39]:
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"]
)

In [40]:
print(train_dataset[0]["text"])

You are a helpful K-12 academic assistant. Answer the student's question using the provided academic context.

Subject: Mixed
Grade Band: K-12
Topic: photosynthesis

Context:
This example is about photosynthesis in a K-12 academic setting.

Question:
Why is photosynthesis important?

Answer:
Photosynthesis is important because it helps plants make food and supports life on Earth.

In [44]:
training_args = TrainingArguments(
    output_dir="./qwen_k12_qlora",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    num_train_epochs=3,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    bf16=True,
    fp16=False,
    report_to="none"
)

In [45]:
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    peft_config=lora_config
)

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

Adding EOS to train dataset:   0%|          | 0/203 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/203 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/203 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/23 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/23 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/23 [00:00<?, ? examples/s]

In [46]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1181: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

TrainOutput(global_step=39, training_loss=1.5309574665167394, metrics={'train_runtime': 64.1212, 'train_samples_per_second': 9.498, 'train_steps_per_second': 0.608, 'total_flos': 426414018677760.0, 'train_loss': 1.5309574665167394})

In [47]:
eval_results = trainer.evaluate()
eval_results

{'eval_loss': 0.9811937808990479,
 'eval_runtime': 0.7407,
 'eval_samples_per_second': 31.051,
 'eval_steps_per_second': 8.1}

In [48]:
trainer.model.save_pretrained("./qwen_k12_qlora_adapter")
tokenizer.save_pretrained("./qwen_k12_qlora_adapter")

('./qwen_k12_qlora_adapter/tokenizer_config.json',
 './qwen_k12_qlora_adapter/chat_template.jinja',
 './qwen_k12_qlora_adapter/tokenizer.json')

In [49]:
prompt = """You are a helpful K-12 academic assistant. Answer the student's question using the provided academic context.

Subject: Science
Grade Band: 4-7
Topic: photosynthesis

Context:
Photosynthesis is the process plants use to make food using sunlight, water, and carbon dioxide.

Question:
What is photosynthesis?

Answer:
"""

In [50]:
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=80,
        do_sample=False
    )

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

You are a helpful K-12 academic assistant. Answer the student's question using the provided academic context.

Subject: Science
Grade Band: 4-7
Topic: photosynthesis

Context:
Photosynthesis is the process plants use to make food using sunlight, water, and carbon dioxide.

Question:
What is photosynthesis?

Answer:
Photosynthesis is the process that plants use to make their own food with sunlight, water, and carbon dioxide. It helps them grow big and strong. Kids can learn about it in school science classes. They also do experiments at home or in nature to see how plants turn sunlight into energy. The answer explains the concept of photosynthesis in simple terms suitable for grade band 4-7 students.